- name: demo of course variable
  hosts: localhost
  connection: local
  vars_file:
    -course.yaml
  tasks:
  - name: print information
    debug:
      msg: "Hi, I am learning Ansible,Course name is {{ COURSE }}, and trainer is {{ TRAINER }}, and duration is {{ DURATION }}"
