- name: demo of prompt variable
  hosts: localhost
  connection: local
  vars_prompt:
  - name: enter_course
    prompt: "Please enter course name"
    private: no
  - name: enter_trainer
    prompt: "Please enter trainer name"
    private: no
  - name: enter_duration
    prompt: "please enter course duration"
    private: no
  tasks:
  - name: print information
    debug:
      msg: "Hi, I am learning Ansible,Course name is {{ enter_course }}, and trainer is {{ enter_trainer }}, and duration is {{ enter_duration }}"