- name: demo on datatypes
  hosts: localhost
  connection: local
  vars:
    Course_name: "Devops with Aiops"    #string
    Duration: 150  #integer/number
    is_live_sessions: true   #bool
    topics:   # list
    - Linux
    - Shell
    - Ansible
    more_deatsils: #map
      months: "5"
      trainer: "siva kumar reddy"
    tasks:
    - name: print information
      msg: |
        name of the course: {{ Course_name }}     
        duration in hrs: {{ Duration }}
        is it live sessions: {{ is_live_sessions }}    
        Topics are: {{ topics }}
        more deatails: {{ more topics }}  
      