- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: Linux, Shell, Ansible, Terraform
    tagmap:
      name: Ansible
      project: Roboshop
      Environment: Dev
    Full_name: Siva Kumar reddy
    taglist: [
        {
            "key": "name",
            "value": "Ansible"
        },
        {
            "key": "project",
            "value": "Roboshop"
        },
        {
            "key": "Environment",
            "value": "Dev"
        }
    ]

  tasks:
  - name: convert string to list
    debug:
      msg: "Topics are: {{ topics | split (',') }}"
  - name: Set default value
    debug:
      msg: " Hi, {{ GREETING | default( ' Good Morning' ) }}"
  - name: convert map to list
    debug:
      msg: "{{ tagmap | dict2items }}"

  - name: convert list to string
    debug:
      msg: "{{ taglist | items2dict }}"
  - name: convert to uppercase
    debug:
      msg: " {{ Full_name | upper }}"
       