- name: "Install apche we serve"
  hosts: frontend
  become: true
  tasks:
    - name: "Install apache and start the service"
      apt:
          name: apache2
          state: present
    - name: "Start the apache2 service"
      service:  
          name: apache2
          state: started

    