[frontend]
172.31.36.208 host_name="frontend.com" #individual host variable   
#172.31.44.247 host_name="backend.com"


[local]
localhost

#[frontend]       
#host_name="frontend.com"   #-----group host variable
#host_name="backend.com"
